### PR TITLE
collapsible (show more/less) social block

### PR DESCRIPTION
**Pull request by shsteimer**
Show more/less on the social block, needed for wgc dell match play site.

Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/shsteimer/social
- After: https://block-social-collapsible--theplayers--hlxsites.hlx.page/drafts/shsteimer/social
- Collapsible: https://block-social-collapsible--theplayers--hlxsites.hlx.page/drafts/shsteimer/social-collapsible

### CODE REVIEW

**Comment by fkakatie** [comment]
very cool! the row for the collapsable property is messing up the profiles generation in the first tile.

Screen Shot 2022-10-03 at 10 21 39 AM

let me take a look... i know what's wrong.

**Review by fkakatie — APPROVED** [review]
I would love to resolve the CLS for the default/twitter variant, but the sizes are so dynamic that i think any attempt to resolve would just generate _different_ CLS... wdyt?

**Comment by shsteimer** [comment]
@fkakatie I added a min-height which then gets removed once everything is loaded. That seems to fix the CLS, but still has issues with TBT, and SI is a bit variable for reasons I'm not sure I grok.

Honestly not sure it's worth it cus we're always at the mercy of twitter. let me know what you think.

**Comment by fkakatie** [comment]
@shsteimer, totally agree. i think what you've done is great.

**Pull request merged**
